### ISSUE TITLE
this is a great little app, thank you :)

### ISSUE THREAD

**Issue by iambumblehead** [waf/thai-characters#1]
Hello,

I wanted to say thank you this is a great app. It is simple, it looks nice, works in a browser or phone and everything is sized nicely -- nice :)

**Comment by waf** [comment]
Thanks! I appreciate the kind words. If you're finding this useful, you might also be interested in these other repos:

- A flash card web app for learning simple vocab: https://fuqua.io/flash-cards/ (source code is at https://github.com/waf/flash-cards).
- A large, categorized deck of vocab words that can be imported into the Anki app: https://github.com/waf/anki-thai

**Comment by iambumblehead** [comment]
I'll check those out when I'm further along... I only know one or two thai things so far :)
